# Curso: Aprendizaje Automático
# Tarea1 - Normalización y Estandarización
## Alonso Nuñez Sanchez
## Fecha de entrega: 22 julio 2019


### Importar dependencias:

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

### Importar archivo de datos
El archivo cargado es una modificación del original suministrado, contiene solo 1 columna (las temperaturas), y no tiene título (encabezado de columna)

In [2]:
#método1: cargar el archivo de una ubicación local en la computadora donde se ejecuta,
#en el mismo directorio del archivo .ipynb

#archivo = 'daily-min-temperatures1.csv'
#dataset = np.array (np.loadtxt(archivo))  #carga una matriz (array numpy) con los datos del archivo (temperaturas)
        
#--------------------------------------------------------------

#método2: cargar el archivo desde un url:

url = 'https://raw.githubusercontent.com/anunezcr/aprendAutom_Tarea1/master/daily-min-temperatures1.csv'       
dataset = np.array (pd.read_csv(url, header=None))  #carga una matriz (array numpy) con los datos del archivo (temperaturas)
print (dataset)

[[20.7]
 [17.9]
 [18.8]
 ...
 [13.5]
 [15.7]
 [13. ]]


### Normalizar y Estandarizar sin usar librerías:

In [3]:
tempOrig = dataset   #tempOrig es el dataset con las instancias originales (temperaturas originales observadas)

maximo = max(tempOrig)   #valor máximo de todas las instancias
minimo = min(tempOrig)   #valor mínimo de todas las intancias
media = np.mean(tempOrig) #media de las instancias
desvStd = np.std(tempOrig) #desviación estandar de las instancias

#usando operaciones sobre matrices (el dataset original es una matriz/array)
tempNorm = (tempOrig - minimo) / (maximo - minimo)  #tempNorm es la normalización de las temperaturas originales
tempEstand = (tempOrig - media) / desvStd           #tempEstadn es la estandarización de las temperaturas originales

print("Máximo:       ", maximo)
print("Mínimo:       ", minimo)
print("Media:        ", media)
print("DesvEstandar: ", desvStd,"\n")

print("Original:\n", tempOrig, "\n")
print("Normalizado:\n", tempNorm, "\n")
print("Estandarizado:\n", tempEstand)

Máximo:        [26.3]
Mínimo:        [0.]
Media:         11.177753424657535
DesvEstandar:  4.071279075310806 

Original:
 [[20.7]
 [17.9]
 [18.8]
 ...
 [13.5]
 [15.7]
 [13. ]] 

Normalizado:
 [[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]] 

Estandarizado:
 [[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]


### Normalizar usando libreria scikit-learn 
### Función MinMaxScaler()

In [4]:
#Normalizar:

df = pd.DataFrame(tempOrig)   #cargar los datos originales en un DataFrame de Pandas

#normalizar el DataFrame:
scalerNrm = MinMaxScaler()
tempNormSKL = scalerNrm.fit_transform(df)  

print("Normalizado con skl: \n", tempNormSKL)

Normalizado con skl: 
 [[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]


### Estandarizar usando libreria scikit-learn

### Función StandarScaler()

In [5]:
#Estandarizar:

df1 = pd.DataFrame(tempOrig)   #cargar los datos originales en un DataFrame de Pandas

#estandarizar el DataFrame:
scalerStd = StandardScaler()
tempEstandSKL = scalerStd.fit_transform(df1) 

print("Estandarizado con skl: \n", tempEstandSKL)

Estandarizado con skl: 
 [[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]
